{
 "title": "JVM resource dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current threads",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"minitwit-java\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocked threads",
   "type": "gauge",
   "description": "Should always be 0",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_deadlocked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"} / jvm_memory_bytes_max{area=\"heap\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}