{
 "title": "Postgres Database - Dashboard",
 "time": { "from": "now-1w/w", "to": "now-1w/w" },
 "panels": [
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "minitwitdb",
     "rawSql": "SELECT COUNT(*) AS total_users FROM users"
    }
   ]
  },
  {
   "title": "Total messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "minitwitdb",
     "rawSql": "SELECT COUNT(*) AS total_messages FROM message"
    }
   ]
  },
  {
   "title": "Total following",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "minitwitdb",
     "rawSql": "SELECT COUNT(*) AS total_following FROM follower"
    }
   ]
  }
 ]
}