# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "minitwit" do |minitwit|
    minitwit.vm.box = "digital_ocean"
    minitwit.vm.provider :digital_ocean do |provider|
      provider.token = ENV["DIGITAL_OCEAN_KEY"]
      provider.ssh_key_name = 'Magnus_Mac'

      provider.image = "ubuntu-22-04-x64"
      provider.region = "fra1"
      provider.size = "s-1vcpu-1gb"
    end
  # CHANGE THIS LINE IF THE SSH FOLDER IS DIFFERENT. 
  config.ssh.private_key_path = '~/.ssh/id_ed25519'
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provision "shell", path: "provision_keys.sh"
  config.vm.provision "shell", path: "provision.sh"
end