{
 "title": "HTTP Requests - Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "url_path",
    "label": "Filter",
    "query": "API : ^/api.*, Web : ^/web.*, Both : ^/(api|web).*"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "description": "Rate of incoming HTTP requests per second, broken down by endpoint and status code. Shows current traffic volume and patterns over time.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(minitwit_http_requests_total{job=\"minitwit-java\", path=~\"$url_path\"}[$__rate_interval])) by (status, path)",
     "legendFormat": "{{status}} - {{path}}"
    }
   ]
  },
  {
   "title": "Request Failure Rate (4xx/5xx) ",
   "type": "bargauge",
   "description": "Shows the percentage of failed HTTP requests per endpoint. 4xx errors are client-side issues (e.g. 404 Not Found, 401 Unauthorized) meaning the request was invalid. 5xx errors are server-side issues (e.g. 500 Internal Server Error) meaning something went wrong in our application. A high 4xx rate may indicate invalid API calls from the simulator, while any 5xx errors should be investigated immediately.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (path) (rate(minitwit_http_requests_total{status=~\"4..|5..\", path=~\"$url_path\", path!~\"unmatched_route|.*swagger.*\"}[5m]))\n  / \n  sum by (path) (rate(minitwit_http_requests_total{path=~\"$url_path\", path!~\"unmatched_route|.*swagger.*\"}[5m]))\n) \nor \n(\n  sum by (path) (rate(minitwit_http_requests_total{path=~\"$url_path\", path!~\"unmatched_route|.*swagger.*\"}[5m])) * 0\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum_over_time(increase(minitwit_http_requests_total{path=~\"$url_path\"}[5m])[60d:5m])",
     "legendFormat": "{{status}} - {{path}}"
    },
    {
     "expr": "sum(sum_over_time(increase(minitwit_http_requests_total{path=~\"$url_path\"}[5m])[60d:5m]))",
     "legendFormat": "Total (all paths)"
    }
   ]
  },
  {
   "title": "Total Errors (5 min window)",
   "type": "timeseries",
   "description": "Total number of 4xx and 5xx errors per endpoint in the last 5 minutes. 4xx errors indicate client-side issues such as invalid requests or missing resources. 5xx errors indicate server-side failures in our application.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (path, status) (increase(minitwit_http_requests_total{status=~\"4..|5..\", path=~\"$url_path\"}[5m]))",
     "legendFormat": "{{status}} - {{path}}"
    }
   ]
  },
  {
   "title": "Request count per endpoint",
   "type": "barchart",
   "description": "Total number of requests received per API endpoint over the selected time range. Use this alongside the average response time chart to understand whether slow endpoints are handling high or low traffic volumes",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_count{job=\"minitwit-java\", path=~\"$url_path\"}[$__range])",
     "legendFormat": "{{status}} - {{path}}"
    }
   ]
  },
  {
   "title": "Average response time per endpoint (ms)",
   "type": "barchart",
   "description": "Average response time in milliseconds per API endpoint over a 1 hour rolling window. Filtered by the selected path pattern. Values above 80ms are highlighted in red.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (path) (rate(http_request_duration_seconds_sum{job=\"minitwit-java\", path=~\"$url_path\"}[1h]))/avg by (path) (rate(http_request_duration_seconds_count{job=\"minitwit-java\", path=~\"$url_path\"}[1h]))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simulator API Latest Requests",
   "type": "timeseries",
   "description": "Requests to /api/latest. The simulator calls this endpoint to verify which request was last processed by our server. Regular polling indicates the simulator is actively monitoring our API. Gaps in the pattern may indicate the simulator or our server is down.",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (path)(increase(minitwit_http_requests_total{path=\"/api/latest\"}[1h]))",
     "legendFormat": "{{path}}"
    },
    {}
   ]
  },
  {
   "title": "Overall average reponse time ",
   "type": "timeseries",
   "description": "Average response time in seconds across all API endpoints combined, shown as a time series over the selected time range. Spikes indicate periods of degraded performance across the entire API.",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 24 },
   "targets": [
    {
     "expr": "sum(\n    rate(http_request_duration_seconds_sum{job=\"minitwit-java\", path=~\"/api/.*\"}[1h])\n    )\n/\nsum(\n    rate(http_request_duration_seconds_count{job=\"minitwit-java\", path=~\"/api/.*\"}[1h])\n    )",
     "legendFormat": "Time in seconds"
    }
   ]
  },
  {
   "title": "Svelte logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/minitwit-svelte-frontend-1\"}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"/minitwit-nginx-1\"} |= \"404\""
    }
   ]
  },
  {
   "title": "Registration Activity",
   "type": "timeseries",
   "description": "Total user registration requests from the simulator API (/api/register) and web app (/web/auth/register). Split by status code to show successful registrations (2xx) vs failed attempts (4xx, e.g. duplicate username or missing fields).",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 38 },
   "targets": [
    {
     "expr": "sum by (path, status) (\n  increase(minitwit_http_requests_total{\n    path=~\"$url_path\", \n    path=~\".*register$\"\n  }[1h])\n)",
     "legendFormat": "{{status}} - {{path}}"
    }
   ]
  }
 ]
}